version: "3"
services:
  app:
    depends_on:
     - db
    image: socialworky/worky-message-dev:${GIT_SHA}
    restart: always
    container_name: worky-message-dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SSL: ${DB_SSL}
      JWT_SECRET: ${JWT_SECRET}
      API_BACKEND_URL: ${API_BACKEND_URL}
    dns:
      - 1.1.1.1
  db:
    container_name: postgres-messageDB
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-db-message:/var/lib/postgresql/data
  
  pgAdmin:
    depends_on:
      - db
    container_name: pgAdmin-message
    image: dpage/pgadmin4:6.17
    restart: always
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    volumes:
      - pgadmin-data-message:/var/lib/pgadmin

volumes:
  postgres-db-message:
    external: false
  pgadmin-data-message:
    external: false
